export const MODULE_PATHS: Record<string, string> = {
  tickets: "/app/tickets",
  assets: "/app/assets",
  maintenance: "/app/maintenance",
  inventory: "/app/inventory",
  suppliers: "/app/suppliers",
  contracts: "/app/contracts",
  work_orders: "/app/work-orders",
  purchase_orders: "/app/purchase-orders",
  utilities: "/app/utilities",
  invoices: "/app/invoices",
  reports: "/app/reports",
  sla: "/app/sla",
  penalties: "/app/penalties",
  users: "/app/users",
  audit: "/app/audit",
  docs: "/app/docs",
  settings: "/app/settings",
  messages: "/app/messages",
  statistics: "/app/statistics",
  cashbook: "/app/cashbook",
  smart_inbox: "/app/smart-inbox",
  sustainability: "/app/sustainability",
  scheduled_exports: "/app/scheduled-exports",
  alerts: "/app/alerts",
  overview: "/app/overview",
  housekeeping: "/app/housekeeping",
  guest_issues: "/app/guest-issues",
  rooms: "/app/structures",
  sla_settings: "/app/sla-settings",
  notifications: "/app/notifications",
  delegations: "/app/delegations",
  organization: "/app/organization",
  integrations: "/app/integrations",
};
export const moduleHref = (m?: string | null) => (m && MODULE_PATHS[m]) || "/app";
