/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GQrRouteImport } from './routes/g.$qr'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as ApiTtsSpeakRouteImport } from './routes/api/tts/speak'
import { Route as AuthenticatedAppWorkflowsRouteImport } from './routes/_authenticated/app.workflows'
import { Route as AuthenticatedAppWorkOrdersRouteImport } from './routes/_authenticated/app.work-orders'
import { Route as AuthenticatedAppUtilitiesRouteImport } from './routes/_authenticated/app.utilities'
import { Route as AuthenticatedAppUsersRouteImport } from './routes/_authenticated/app.users'
import { Route as AuthenticatedAppTrendsRouteImport } from './routes/_authenticated/app.trends'
import { Route as AuthenticatedAppTicketsRouteImport } from './routes/_authenticated/app.tickets'
import { Route as AuthenticatedAppSustainabilityRouteImport } from './routes/_authenticated/app.sustainability'
import { Route as AuthenticatedAppSuppliersComplianceRouteImport } from './routes/_authenticated/app.suppliers-compliance'
import { Route as AuthenticatedAppSuppliersRouteImport } from './routes/_authenticated/app.suppliers'
import { Route as AuthenticatedAppStructuresRouteImport } from './routes/_authenticated/app.structures'
import { Route as AuthenticatedAppStructureKpiRouteImport } from './routes/_authenticated/app.structure-kpi'
import { Route as AuthenticatedAppStatisticsRouteImport } from './routes/_authenticated/app.statistics'
import { Route as AuthenticatedAppSmartInboxRouteImport } from './routes/_authenticated/app.smart-inbox'
import { Route as AuthenticatedAppSlaSettingsRouteImport } from './routes/_authenticated/app.sla-settings'
import { Route as AuthenticatedAppSlaNotificationsRouteImport } from './routes/_authenticated/app.sla-notifications'
import { Route as AuthenticatedAppSlaEscalationsRouteImport } from './routes/_authenticated/app.sla-escalations'
import { Route as AuthenticatedAppSlaComplianceRouteImport } from './routes/_authenticated/app.sla-compliance'
import { Route as AuthenticatedAppSlaRouteImport } from './routes/_authenticated/app.sla'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppScheduledExportsRouteImport } from './routes/_authenticated/app.scheduled-exports'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated/app.reports'
import { Route as AuthenticatedAppReportBuilderRouteImport } from './routes/_authenticated/app.report-builder'
import { Route as AuthenticatedAppReordersRouteImport } from './routes/_authenticated/app.reorders'
import { Route as AuthenticatedAppPurchaseOrdersRouteImport } from './routes/_authenticated/app.purchase-orders'
import { Route as AuthenticatedAppPermissionsRouteImport } from './routes/_authenticated/app.permissions'
import { Route as AuthenticatedAppPenaltiesRouteImport } from './routes/_authenticated/app.penalties'
import { Route as AuthenticatedAppOverviewRouteImport } from './routes/_authenticated/app.overview'
import { Route as AuthenticatedAppOnboardingRouteImport } from './routes/_authenticated/app.onboarding'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app.notifications'
import { Route as AuthenticatedAppMessagesRouteImport } from './routes/_authenticated/app.messages'
import { Route as AuthenticatedAppMaintenanceRouteImport } from './routes/_authenticated/app.maintenance'
import { Route as AuthenticatedAppInvoicesRouteImport } from './routes/_authenticated/app.invoices'
import { Route as AuthenticatedAppInventoryRouteImport } from './routes/_authenticated/app.inventory'
import { Route as AuthenticatedAppIntegrationsRouteImport } from './routes/_authenticated/app.integrations'
import { Route as AuthenticatedAppHousekeepingRouteImport } from './routes/_authenticated/app.housekeeping'
import { Route as AuthenticatedAppGuestIssuesRouteImport } from './routes/_authenticated/app.guest-issues'
import { Route as AuthenticatedAppDocsRouteImport } from './routes/_authenticated/app.docs'
import { Route as AuthenticatedAppDeliveryQueueRouteImport } from './routes/_authenticated/app.delivery-queue'
import { Route as AuthenticatedAppDelegationsHistoryRouteImport } from './routes/_authenticated/app.delegations-history'
import { Route as AuthenticatedAppDelegationsRouteImport } from './routes/_authenticated/app.delegations'
import { Route as AuthenticatedAppDelegationAuditRouteImport } from './routes/_authenticated/app.delegation-audit'
import { Route as AuthenticatedAppCostAnalyticsRouteImport } from './routes/_authenticated/app.cost-analytics'
import { Route as AuthenticatedAppContractsRouteImport } from './routes/_authenticated/app.contracts'
import { Route as AuthenticatedAppCashbookRouteImport } from './routes/_authenticated/app.cashbook'
import { Route as AuthenticatedAppAuditRouteImport } from './routes/_authenticated/app.audit'
import { Route as AuthenticatedAppAssetsRouteImport } from './routes/_authenticated/app.assets'
import { Route as AuthenticatedAppAreaMappingRouteImport } from './routes/_authenticated/app.area-mapping'
import { Route as AuthenticatedAppAlertsRouteImport } from './routes/_authenticated/app.alerts'
import { Route as ApiPublicHooksSlaNotifyRouteImport } from './routes/api/public/hooks/sla-notify'
import { Route as ApiPublicHooksSlaEscalationsRouteImport } from './routes/api/public/hooks/sla-escalations'
import { Route as ApiPublicHooksReportSchedulerRouteImport } from './routes/api/public/hooks/report-scheduler'
import { Route as ApiPublicHooksContractsNotifyRouteImport } from './routes/api/public/hooks/contracts-notify'
import { Route as AuthenticatedAppTicketsIdRouteImport } from './routes/_authenticated/app.tickets.$id'
import { Route as AuthenticatedAppReordersIdRouteImport } from './routes/_authenticated/app.reorders.$id'
import { Route as AuthenticatedAppDeliveryQueueIdRouteImport } from './routes/_authenticated/app.delivery-queue.$id'
import { Route as AuthenticatedAppAssetsIdRouteImport } from './routes/_authenticated/app.assets.$id'
import { Route as AuthenticatedAppAQrRouteImport } from './routes/_authenticated/app.a.$qr'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GQrRoute = GQrRouteImport.update({
  id: '/g/$qr',
  path: '/g/$qr',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiTtsSpeakRoute = ApiTtsSpeakRouteImport.update({
  id: '/api/tts/speak',
  path: '/api/tts/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppWorkflowsRoute =
  AuthenticatedAppWorkflowsRouteImport.update({
    id: '/app/workflows',
    path: '/app/workflows',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppWorkOrdersRoute =
  AuthenticatedAppWorkOrdersRouteImport.update({
    id: '/app/work-orders',
    path: '/app/work-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppUtilitiesRoute =
  AuthenticatedAppUtilitiesRouteImport.update({
    id: '/app/utilities',
    path: '/app/utilities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppUsersRoute = AuthenticatedAppUsersRouteImport.update({
  id: '/app/users',
  path: '/app/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppTrendsRoute = AuthenticatedAppTrendsRouteImport.update({
  id: '/app/trends',
  path: '/app/trends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppTicketsRoute = AuthenticatedAppTicketsRouteImport.update({
  id: '/app/tickets',
  path: '/app/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSustainabilityRoute =
  AuthenticatedAppSustainabilityRouteImport.update({
    id: '/app/sustainability',
    path: '/app/sustainability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSuppliersComplianceRoute =
  AuthenticatedAppSuppliersComplianceRouteImport.update({
    id: '/app/suppliers-compliance',
    path: '/app/suppliers-compliance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSuppliersRoute =
  AuthenticatedAppSuppliersRouteImport.update({
    id: '/app/suppliers',
    path: '/app/suppliers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppStructuresRoute =
  AuthenticatedAppStructuresRouteImport.update({
    id: '/app/structures',
    path: '/app/structures',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppStructureKpiRoute =
  AuthenticatedAppStructureKpiRouteImport.update({
    id: '/app/structure-kpi',
    path: '/app/structure-kpi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppStatisticsRoute =
  AuthenticatedAppStatisticsRouteImport.update({
    id: '/app/statistics',
    path: '/app/statistics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSmartInboxRoute =
  AuthenticatedAppSmartInboxRouteImport.update({
    id: '/app/smart-inbox',
    path: '/app/smart-inbox',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlaSettingsRoute =
  AuthenticatedAppSlaSettingsRouteImport.update({
    id: '/app/sla-settings',
    path: '/app/sla-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlaNotificationsRoute =
  AuthenticatedAppSlaNotificationsRouteImport.update({
    id: '/app/sla-notifications',
    path: '/app/sla-notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlaEscalationsRoute =
  AuthenticatedAppSlaEscalationsRouteImport.update({
    id: '/app/sla-escalations',
    path: '/app/sla-escalations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlaComplianceRoute =
  AuthenticatedAppSlaComplianceRouteImport.update({
    id: '/app/sla-compliance',
    path: '/app/sla-compliance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlaRoute = AuthenticatedAppSlaRouteImport.update({
  id: '/app/sla',
  path: '/app/sla',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/app/settings',
    path: '/app/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppScheduledExportsRoute =
  AuthenticatedAppScheduledExportsRouteImport.update({
    id: '/app/scheduled-exports',
    path: '/app/scheduled-exports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/app/reports',
  path: '/app/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppReportBuilderRoute =
  AuthenticatedAppReportBuilderRouteImport.update({
    id: '/app/report-builder',
    path: '/app/report-builder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppReordersRoute =
  AuthenticatedAppReordersRouteImport.update({
    id: '/app/reorders',
    path: '/app/reorders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPurchaseOrdersRoute =
  AuthenticatedAppPurchaseOrdersRouteImport.update({
    id: '/app/purchase-orders',
    path: '/app/purchase-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPermissionsRoute =
  AuthenticatedAppPermissionsRouteImport.update({
    id: '/app/permissions',
    path: '/app/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPenaltiesRoute =
  AuthenticatedAppPenaltiesRouteImport.update({
    id: '/app/penalties',
    path: '/app/penalties',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppOverviewRoute =
  AuthenticatedAppOverviewRouteImport.update({
    id: '/app/overview',
    path: '/app/overview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppOnboardingRoute =
  AuthenticatedAppOnboardingRouteImport.update({
    id: '/app/onboarding',
    path: '/app/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/app/notifications',
    path: '/app/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppMessagesRoute =
  AuthenticatedAppMessagesRouteImport.update({
    id: '/app/messages',
    path: '/app/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppMaintenanceRoute =
  AuthenticatedAppMaintenanceRouteImport.update({
    id: '/app/maintenance',
    path: '/app/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppInvoicesRoute =
  AuthenticatedAppInvoicesRouteImport.update({
    id: '/app/invoices',
    path: '/app/invoices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppInventoryRoute =
  AuthenticatedAppInventoryRouteImport.update({
    id: '/app/inventory',
    path: '/app/inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppIntegrationsRoute =
  AuthenticatedAppIntegrationsRouteImport.update({
    id: '/app/integrations',
    path: '/app/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppHousekeepingRoute =
  AuthenticatedAppHousekeepingRouteImport.update({
    id: '/app/housekeeping',
    path: '/app/housekeeping',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppGuestIssuesRoute =
  AuthenticatedAppGuestIssuesRouteImport.update({
    id: '/app/guest-issues',
    path: '/app/guest-issues',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDocsRoute = AuthenticatedAppDocsRouteImport.update({
  id: '/app/docs',
  path: '/app/docs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppDeliveryQueueRoute =
  AuthenticatedAppDeliveryQueueRouteImport.update({
    id: '/app/delivery-queue',
    path: '/app/delivery-queue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDelegationsHistoryRoute =
  AuthenticatedAppDelegationsHistoryRouteImport.update({
    id: '/app/delegations-history',
    path: '/app/delegations-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDelegationsRoute =
  AuthenticatedAppDelegationsRouteImport.update({
    id: '/app/delegations',
    path: '/app/delegations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDelegationAuditRoute =
  AuthenticatedAppDelegationAuditRouteImport.update({
    id: '/app/delegation-audit',
    path: '/app/delegation-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCostAnalyticsRoute =
  AuthenticatedAppCostAnalyticsRouteImport.update({
    id: '/app/cost-analytics',
    path: '/app/cost-analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppContractsRoute =
  AuthenticatedAppContractsRouteImport.update({
    id: '/app/contracts',
    path: '/app/contracts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCashbookRoute =
  AuthenticatedAppCashbookRouteImport.update({
    id: '/app/cashbook',
    path: '/app/cashbook',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAuditRoute = AuthenticatedAppAuditRouteImport.update({
  id: '/app/audit',
  path: '/app/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAssetsRoute = AuthenticatedAppAssetsRouteImport.update({
  id: '/app/assets',
  path: '/app/assets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAreaMappingRoute =
  AuthenticatedAppAreaMappingRouteImport.update({
    id: '/app/area-mapping',
    path: '/app/area-mapping',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAlertsRoute = AuthenticatedAppAlertsRouteImport.update({
  id: '/app/alerts',
  path: '/app/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksSlaNotifyRoute = ApiPublicHooksSlaNotifyRouteImport.update({
  id: '/api/public/hooks/sla-notify',
  path: '/api/public/hooks/sla-notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSlaEscalationsRoute =
  ApiPublicHooksSlaEscalationsRouteImport.update({
    id: '/api/public/hooks/sla-escalations',
    path: '/api/public/hooks/sla-escalations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksReportSchedulerRoute =
  ApiPublicHooksReportSchedulerRouteImport.update({
    id: '/api/public/hooks/report-scheduler',
    path: '/api/public/hooks/report-scheduler',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksContractsNotifyRoute =
  ApiPublicHooksContractsNotifyRouteImport.update({
    id: '/api/public/hooks/contracts-notify',
    path: '/api/public/hooks/contracts-notify',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppTicketsIdRoute =
  AuthenticatedAppTicketsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppTicketsRoute,
  } as any)
const AuthenticatedAppReordersIdRoute =
  AuthenticatedAppReordersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppReordersRoute,
  } as any)
const AuthenticatedAppDeliveryQueueIdRoute =
  AuthenticatedAppDeliveryQueueIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppDeliveryQueueRoute,
  } as any)
const AuthenticatedAppAssetsIdRoute =
  AuthenticatedAppAssetsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppAssetsRoute,
  } as any)
const AuthenticatedAppAQrRoute = AuthenticatedAppAQrRouteImport.update({
  id: '/app/a/$qr',
  path: '/app/a/$qr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/g/$qr': typeof GQrRoute
  '/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/app/area-mapping': typeof AuthenticatedAppAreaMappingRoute
  '/app/assets': typeof AuthenticatedAppAssetsRouteWithChildren
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/cashbook': typeof AuthenticatedAppCashbookRoute
  '/app/contracts': typeof AuthenticatedAppContractsRoute
  '/app/cost-analytics': typeof AuthenticatedAppCostAnalyticsRoute
  '/app/delegation-audit': typeof AuthenticatedAppDelegationAuditRoute
  '/app/delegations': typeof AuthenticatedAppDelegationsRoute
  '/app/delegations-history': typeof AuthenticatedAppDelegationsHistoryRoute
  '/app/delivery-queue': typeof AuthenticatedAppDeliveryQueueRouteWithChildren
  '/app/docs': typeof AuthenticatedAppDocsRoute
  '/app/guest-issues': typeof AuthenticatedAppGuestIssuesRoute
  '/app/housekeeping': typeof AuthenticatedAppHousekeepingRoute
  '/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/app/inventory': typeof AuthenticatedAppInventoryRoute
  '/app/invoices': typeof AuthenticatedAppInvoicesRoute
  '/app/maintenance': typeof AuthenticatedAppMaintenanceRoute
  '/app/messages': typeof AuthenticatedAppMessagesRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/overview': typeof AuthenticatedAppOverviewRoute
  '/app/penalties': typeof AuthenticatedAppPenaltiesRoute
  '/app/permissions': typeof AuthenticatedAppPermissionsRoute
  '/app/purchase-orders': typeof AuthenticatedAppPurchaseOrdersRoute
  '/app/reorders': typeof AuthenticatedAppReordersRouteWithChildren
  '/app/report-builder': typeof AuthenticatedAppReportBuilderRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/scheduled-exports': typeof AuthenticatedAppScheduledExportsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/sla': typeof AuthenticatedAppSlaRoute
  '/app/sla-compliance': typeof AuthenticatedAppSlaComplianceRoute
  '/app/sla-escalations': typeof AuthenticatedAppSlaEscalationsRoute
  '/app/sla-notifications': typeof AuthenticatedAppSlaNotificationsRoute
  '/app/sla-settings': typeof AuthenticatedAppSlaSettingsRoute
  '/app/smart-inbox': typeof AuthenticatedAppSmartInboxRoute
  '/app/statistics': typeof AuthenticatedAppStatisticsRoute
  '/app/structure-kpi': typeof AuthenticatedAppStructureKpiRoute
  '/app/structures': typeof AuthenticatedAppStructuresRoute
  '/app/suppliers': typeof AuthenticatedAppSuppliersRoute
  '/app/suppliers-compliance': typeof AuthenticatedAppSuppliersComplianceRoute
  '/app/sustainability': typeof AuthenticatedAppSustainabilityRoute
  '/app/tickets': typeof AuthenticatedAppTicketsRouteWithChildren
  '/app/trends': typeof AuthenticatedAppTrendsRoute
  '/app/users': typeof AuthenticatedAppUsersRoute
  '/app/utilities': typeof AuthenticatedAppUtilitiesRoute
  '/app/work-orders': typeof AuthenticatedAppWorkOrdersRoute
  '/app/workflows': typeof AuthenticatedAppWorkflowsRoute
  '/api/tts/speak': typeof ApiTtsSpeakRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/a/$qr': typeof AuthenticatedAppAQrRoute
  '/app/assets/$id': typeof AuthenticatedAppAssetsIdRoute
  '/app/delivery-queue/$id': typeof AuthenticatedAppDeliveryQueueIdRoute
  '/app/reorders/$id': typeof AuthenticatedAppReordersIdRoute
  '/app/tickets/$id': typeof AuthenticatedAppTicketsIdRoute
  '/api/public/hooks/contracts-notify': typeof ApiPublicHooksContractsNotifyRoute
  '/api/public/hooks/report-scheduler': typeof ApiPublicHooksReportSchedulerRoute
  '/api/public/hooks/sla-escalations': typeof ApiPublicHooksSlaEscalationsRoute
  '/api/public/hooks/sla-notify': typeof ApiPublicHooksSlaNotifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/g/$qr': typeof GQrRoute
  '/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/app/area-mapping': typeof AuthenticatedAppAreaMappingRoute
  '/app/assets': typeof AuthenticatedAppAssetsRouteWithChildren
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/cashbook': typeof AuthenticatedAppCashbookRoute
  '/app/contracts': typeof AuthenticatedAppContractsRoute
  '/app/cost-analytics': typeof AuthenticatedAppCostAnalyticsRoute
  '/app/delegation-audit': typeof AuthenticatedAppDelegationAuditRoute
  '/app/delegations': typeof AuthenticatedAppDelegationsRoute
  '/app/delegations-history': typeof AuthenticatedAppDelegationsHistoryRoute
  '/app/delivery-queue': typeof AuthenticatedAppDeliveryQueueRouteWithChildren
  '/app/docs': typeof AuthenticatedAppDocsRoute
  '/app/guest-issues': typeof AuthenticatedAppGuestIssuesRoute
  '/app/housekeeping': typeof AuthenticatedAppHousekeepingRoute
  '/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/app/inventory': typeof AuthenticatedAppInventoryRoute
  '/app/invoices': typeof AuthenticatedAppInvoicesRoute
  '/app/maintenance': typeof AuthenticatedAppMaintenanceRoute
  '/app/messages': typeof AuthenticatedAppMessagesRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/overview': typeof AuthenticatedAppOverviewRoute
  '/app/penalties': typeof AuthenticatedAppPenaltiesRoute
  '/app/permissions': typeof AuthenticatedAppPermissionsRoute
  '/app/purchase-orders': typeof AuthenticatedAppPurchaseOrdersRoute
  '/app/reorders': typeof AuthenticatedAppReordersRouteWithChildren
  '/app/report-builder': typeof AuthenticatedAppReportBuilderRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/scheduled-exports': typeof AuthenticatedAppScheduledExportsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/sla': typeof AuthenticatedAppSlaRoute
  '/app/sla-compliance': typeof AuthenticatedAppSlaComplianceRoute
  '/app/sla-escalations': typeof AuthenticatedAppSlaEscalationsRoute
  '/app/sla-notifications': typeof AuthenticatedAppSlaNotificationsRoute
  '/app/sla-settings': typeof AuthenticatedAppSlaSettingsRoute
  '/app/smart-inbox': typeof AuthenticatedAppSmartInboxRoute
  '/app/statistics': typeof AuthenticatedAppStatisticsRoute
  '/app/structure-kpi': typeof AuthenticatedAppStructureKpiRoute
  '/app/structures': typeof AuthenticatedAppStructuresRoute
  '/app/suppliers': typeof AuthenticatedAppSuppliersRoute
  '/app/suppliers-compliance': typeof AuthenticatedAppSuppliersComplianceRoute
  '/app/sustainability': typeof AuthenticatedAppSustainabilityRoute
  '/app/tickets': typeof AuthenticatedAppTicketsRouteWithChildren
  '/app/trends': typeof AuthenticatedAppTrendsRoute
  '/app/users': typeof AuthenticatedAppUsersRoute
  '/app/utilities': typeof AuthenticatedAppUtilitiesRoute
  '/app/work-orders': typeof AuthenticatedAppWorkOrdersRoute
  '/app/workflows': typeof AuthenticatedAppWorkflowsRoute
  '/api/tts/speak': typeof ApiTtsSpeakRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/a/$qr': typeof AuthenticatedAppAQrRoute
  '/app/assets/$id': typeof AuthenticatedAppAssetsIdRoute
  '/app/delivery-queue/$id': typeof AuthenticatedAppDeliveryQueueIdRoute
  '/app/reorders/$id': typeof AuthenticatedAppReordersIdRoute
  '/app/tickets/$id': typeof AuthenticatedAppTicketsIdRoute
  '/api/public/hooks/contracts-notify': typeof ApiPublicHooksContractsNotifyRoute
  '/api/public/hooks/report-scheduler': typeof ApiPublicHooksReportSchedulerRoute
  '/api/public/hooks/sla-escalations': typeof ApiPublicHooksSlaEscalationsRoute
  '/api/public/hooks/sla-notify': typeof ApiPublicHooksSlaNotifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/g/$qr': typeof GQrRoute
  '/_authenticated/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/_authenticated/app/area-mapping': typeof AuthenticatedAppAreaMappingRoute
  '/_authenticated/app/assets': typeof AuthenticatedAppAssetsRouteWithChildren
  '/_authenticated/app/audit': typeof AuthenticatedAppAuditRoute
  '/_authenticated/app/cashbook': typeof AuthenticatedAppCashbookRoute
  '/_authenticated/app/contracts': typeof AuthenticatedAppContractsRoute
  '/_authenticated/app/cost-analytics': typeof AuthenticatedAppCostAnalyticsRoute
  '/_authenticated/app/delegation-audit': typeof AuthenticatedAppDelegationAuditRoute
  '/_authenticated/app/delegations': typeof AuthenticatedAppDelegationsRoute
  '/_authenticated/app/delegations-history': typeof AuthenticatedAppDelegationsHistoryRoute
  '/_authenticated/app/delivery-queue': typeof AuthenticatedAppDeliveryQueueRouteWithChildren
  '/_authenticated/app/docs': typeof AuthenticatedAppDocsRoute
  '/_authenticated/app/guest-issues': typeof AuthenticatedAppGuestIssuesRoute
  '/_authenticated/app/housekeeping': typeof AuthenticatedAppHousekeepingRoute
  '/_authenticated/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/_authenticated/app/inventory': typeof AuthenticatedAppInventoryRoute
  '/_authenticated/app/invoices': typeof AuthenticatedAppInvoicesRoute
  '/_authenticated/app/maintenance': typeof AuthenticatedAppMaintenanceRoute
  '/_authenticated/app/messages': typeof AuthenticatedAppMessagesRoute
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/_authenticated/app/overview': typeof AuthenticatedAppOverviewRoute
  '/_authenticated/app/penalties': typeof AuthenticatedAppPenaltiesRoute
  '/_authenticated/app/permissions': typeof AuthenticatedAppPermissionsRoute
  '/_authenticated/app/purchase-orders': typeof AuthenticatedAppPurchaseOrdersRoute
  '/_authenticated/app/reorders': typeof AuthenticatedAppReordersRouteWithChildren
  '/_authenticated/app/report-builder': typeof AuthenticatedAppReportBuilderRoute
  '/_authenticated/app/reports': typeof AuthenticatedAppReportsRoute
  '/_authenticated/app/scheduled-exports': typeof AuthenticatedAppScheduledExportsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/sla': typeof AuthenticatedAppSlaRoute
  '/_authenticated/app/sla-compliance': typeof AuthenticatedAppSlaComplianceRoute
  '/_authenticated/app/sla-escalations': typeof AuthenticatedAppSlaEscalationsRoute
  '/_authenticated/app/sla-notifications': typeof AuthenticatedAppSlaNotificationsRoute
  '/_authenticated/app/sla-settings': typeof AuthenticatedAppSlaSettingsRoute
  '/_authenticated/app/smart-inbox': typeof AuthenticatedAppSmartInboxRoute
  '/_authenticated/app/statistics': typeof AuthenticatedAppStatisticsRoute
  '/_authenticated/app/structure-kpi': typeof AuthenticatedAppStructureKpiRoute
  '/_authenticated/app/structures': typeof AuthenticatedAppStructuresRoute
  '/_authenticated/app/suppliers': typeof AuthenticatedAppSuppliersRoute
  '/_authenticated/app/suppliers-compliance': typeof AuthenticatedAppSuppliersComplianceRoute
  '/_authenticated/app/sustainability': typeof AuthenticatedAppSustainabilityRoute
  '/_authenticated/app/tickets': typeof AuthenticatedAppTicketsRouteWithChildren
  '/_authenticated/app/trends': typeof AuthenticatedAppTrendsRoute
  '/_authenticated/app/users': typeof AuthenticatedAppUsersRoute
  '/_authenticated/app/utilities': typeof AuthenticatedAppUtilitiesRoute
  '/_authenticated/app/work-orders': typeof AuthenticatedAppWorkOrdersRoute
  '/_authenticated/app/workflows': typeof AuthenticatedAppWorkflowsRoute
  '/api/tts/speak': typeof ApiTtsSpeakRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/a/$qr': typeof AuthenticatedAppAQrRoute
  '/_authenticated/app/assets/$id': typeof AuthenticatedAppAssetsIdRoute
  '/_authenticated/app/delivery-queue/$id': typeof AuthenticatedAppDeliveryQueueIdRoute
  '/_authenticated/app/reorders/$id': typeof AuthenticatedAppReordersIdRoute
  '/_authenticated/app/tickets/$id': typeof AuthenticatedAppTicketsIdRoute
  '/api/public/hooks/contracts-notify': typeof ApiPublicHooksContractsNotifyRoute
  '/api/public/hooks/report-scheduler': typeof ApiPublicHooksReportSchedulerRoute
  '/api/public/hooks/sla-escalations': typeof ApiPublicHooksSlaEscalationsRoute
  '/api/public/hooks/sla-notify': typeof ApiPublicHooksSlaNotifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/portal'
    | '/g/$qr'
    | '/app/alerts'
    | '/app/area-mapping'
    | '/app/assets'
    | '/app/audit'
    | '/app/cashbook'
    | '/app/contracts'
    | '/app/cost-analytics'
    | '/app/delegation-audit'
    | '/app/delegations'
    | '/app/delegations-history'
    | '/app/delivery-queue'
    | '/app/docs'
    | '/app/guest-issues'
    | '/app/housekeeping'
    | '/app/integrations'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/maintenance'
    | '/app/messages'
    | '/app/notifications'
    | '/app/onboarding'
    | '/app/overview'
    | '/app/penalties'
    | '/app/permissions'
    | '/app/purchase-orders'
    | '/app/reorders'
    | '/app/report-builder'
    | '/app/reports'
    | '/app/scheduled-exports'
    | '/app/settings'
    | '/app/sla'
    | '/app/sla-compliance'
    | '/app/sla-escalations'
    | '/app/sla-notifications'
    | '/app/sla-settings'
    | '/app/smart-inbox'
    | '/app/statistics'
    | '/app/structure-kpi'
    | '/app/structures'
    | '/app/suppliers'
    | '/app/suppliers-compliance'
    | '/app/sustainability'
    | '/app/tickets'
    | '/app/trends'
    | '/app/users'
    | '/app/utilities'
    | '/app/work-orders'
    | '/app/workflows'
    | '/api/tts/speak'
    | '/app/'
    | '/app/a/$qr'
    | '/app/assets/$id'
    | '/app/delivery-queue/$id'
    | '/app/reorders/$id'
    | '/app/tickets/$id'
    | '/api/public/hooks/contracts-notify'
    | '/api/public/hooks/report-scheduler'
    | '/api/public/hooks/sla-escalations'
    | '/api/public/hooks/sla-notify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/portal'
    | '/g/$qr'
    | '/app/alerts'
    | '/app/area-mapping'
    | '/app/assets'
    | '/app/audit'
    | '/app/cashbook'
    | '/app/contracts'
    | '/app/cost-analytics'
    | '/app/delegation-audit'
    | '/app/delegations'
    | '/app/delegations-history'
    | '/app/delivery-queue'
    | '/app/docs'
    | '/app/guest-issues'
    | '/app/housekeeping'
    | '/app/integrations'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/maintenance'
    | '/app/messages'
    | '/app/notifications'
    | '/app/onboarding'
    | '/app/overview'
    | '/app/penalties'
    | '/app/permissions'
    | '/app/purchase-orders'
    | '/app/reorders'
    | '/app/report-builder'
    | '/app/reports'
    | '/app/scheduled-exports'
    | '/app/settings'
    | '/app/sla'
    | '/app/sla-compliance'
    | '/app/sla-escalations'
    | '/app/sla-notifications'
    | '/app/sla-settings'
    | '/app/smart-inbox'
    | '/app/statistics'
    | '/app/structure-kpi'
    | '/app/structures'
    | '/app/suppliers'
    | '/app/suppliers-compliance'
    | '/app/sustainability'
    | '/app/tickets'
    | '/app/trends'
    | '/app/users'
    | '/app/utilities'
    | '/app/work-orders'
    | '/app/workflows'
    | '/api/tts/speak'
    | '/app'
    | '/app/a/$qr'
    | '/app/assets/$id'
    | '/app/delivery-queue/$id'
    | '/app/reorders/$id'
    | '/app/tickets/$id'
    | '/api/public/hooks/contracts-notify'
    | '/api/public/hooks/report-scheduler'
    | '/api/public/hooks/sla-escalations'
    | '/api/public/hooks/sla-notify'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/portal'
    | '/g/$qr'
    | '/_authenticated/app/alerts'
    | '/_authenticated/app/area-mapping'
    | '/_authenticated/app/assets'
    | '/_authenticated/app/audit'
    | '/_authenticated/app/cashbook'
    | '/_authenticated/app/contracts'
    | '/_authenticated/app/cost-analytics'
    | '/_authenticated/app/delegation-audit'
    | '/_authenticated/app/delegations'
    | '/_authenticated/app/delegations-history'
    | '/_authenticated/app/delivery-queue'
    | '/_authenticated/app/docs'
    | '/_authenticated/app/guest-issues'
    | '/_authenticated/app/housekeeping'
    | '/_authenticated/app/integrations'
    | '/_authenticated/app/inventory'
    | '/_authenticated/app/invoices'
    | '/_authenticated/app/maintenance'
    | '/_authenticated/app/messages'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/onboarding'
    | '/_authenticated/app/overview'
    | '/_authenticated/app/penalties'
    | '/_authenticated/app/permissions'
    | '/_authenticated/app/purchase-orders'
    | '/_authenticated/app/reorders'
    | '/_authenticated/app/report-builder'
    | '/_authenticated/app/reports'
    | '/_authenticated/app/scheduled-exports'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/sla'
    | '/_authenticated/app/sla-compliance'
    | '/_authenticated/app/sla-escalations'
    | '/_authenticated/app/sla-notifications'
    | '/_authenticated/app/sla-settings'
    | '/_authenticated/app/smart-inbox'
    | '/_authenticated/app/statistics'
    | '/_authenticated/app/structure-kpi'
    | '/_authenticated/app/structures'
    | '/_authenticated/app/suppliers'
    | '/_authenticated/app/suppliers-compliance'
    | '/_authenticated/app/sustainability'
    | '/_authenticated/app/tickets'
    | '/_authenticated/app/trends'
    | '/_authenticated/app/users'
    | '/_authenticated/app/utilities'
    | '/_authenticated/app/work-orders'
    | '/_authenticated/app/workflows'
    | '/api/tts/speak'
    | '/_authenticated/app/'
    | '/_authenticated/app/a/$qr'
    | '/_authenticated/app/assets/$id'
    | '/_authenticated/app/delivery-queue/$id'
    | '/_authenticated/app/reorders/$id'
    | '/_authenticated/app/tickets/$id'
    | '/api/public/hooks/contracts-notify'
    | '/api/public/hooks/report-scheduler'
    | '/api/public/hooks/sla-escalations'
    | '/api/public/hooks/sla-notify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  GQrRoute: typeof GQrRoute
  ApiTtsSpeakRoute: typeof ApiTtsSpeakRoute
  ApiPublicHooksContractsNotifyRoute: typeof ApiPublicHooksContractsNotifyRoute
  ApiPublicHooksReportSchedulerRoute: typeof ApiPublicHooksReportSchedulerRoute
  ApiPublicHooksSlaEscalationsRoute: typeof ApiPublicHooksSlaEscalationsRoute
  ApiPublicHooksSlaNotifyRoute: typeof ApiPublicHooksSlaNotifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$qr': {
      id: '/g/$qr'
      path: '/g/$qr'
      fullPath: '/g/$qr'
      preLoaderRoute: typeof GQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/tts/speak': {
      id: '/api/tts/speak'
      path: '/api/tts/speak'
      fullPath: '/api/tts/speak'
      preLoaderRoute: typeof ApiTtsSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/workflows': {
      id: '/_authenticated/app/workflows'
      path: '/app/workflows'
      fullPath: '/app/workflows'
      preLoaderRoute: typeof AuthenticatedAppWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/work-orders': {
      id: '/_authenticated/app/work-orders'
      path: '/app/work-orders'
      fullPath: '/app/work-orders'
      preLoaderRoute: typeof AuthenticatedAppWorkOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/utilities': {
      id: '/_authenticated/app/utilities'
      path: '/app/utilities'
      fullPath: '/app/utilities'
      preLoaderRoute: typeof AuthenticatedAppUtilitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/users': {
      id: '/_authenticated/app/users'
      path: '/app/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AuthenticatedAppUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/trends': {
      id: '/_authenticated/app/trends'
      path: '/app/trends'
      fullPath: '/app/trends'
      preLoaderRoute: typeof AuthenticatedAppTrendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/tickets': {
      id: '/_authenticated/app/tickets'
      path: '/app/tickets'
      fullPath: '/app/tickets'
      preLoaderRoute: typeof AuthenticatedAppTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/sustainability': {
      id: '/_authenticated/app/sustainability'
      path: '/app/sustainability'
      fullPath: '/app/sustainability'
      preLoaderRoute: typeof AuthenticatedAppSustainabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/suppliers-compliance': {
      id: '/_authenticated/app/suppliers-compliance'
      path: '/app/suppliers-compliance'
      fullPath: '/app/suppliers-compliance'
      preLoaderRoute: typeof AuthenticatedAppSuppliersComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/suppliers': {
      id: '/_authenticated/app/suppliers'
      path: '/app/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AuthenticatedAppSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/structures': {
      id: '/_authenticated/app/structures'
      path: '/app/structures'
      fullPath: '/app/structures'
      preLoaderRoute: typeof AuthenticatedAppStructuresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/structure-kpi': {
      id: '/_authenticated/app/structure-kpi'
      path: '/app/structure-kpi'
      fullPath: '/app/structure-kpi'
      preLoaderRoute: typeof AuthenticatedAppStructureKpiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/statistics': {
      id: '/_authenticated/app/statistics'
      path: '/app/statistics'
      fullPath: '/app/statistics'
      preLoaderRoute: typeof AuthenticatedAppStatisticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/smart-inbox': {
      id: '/_authenticated/app/smart-inbox'
      path: '/app/smart-inbox'
      fullPath: '/app/smart-inbox'
      preLoaderRoute: typeof AuthenticatedAppSmartInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/sla-settings': {
      id: '/_authenticated/app/sla-settings'
      path: '/app/sla-settings'
      fullPath: '/app/sla-settings'
      preLoaderRoute: typeof AuthenticatedAppSlaSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/sla-notifications': {
      id: '/_authenticated/app/sla-notifications'
      path: '/app/sla-notifications'
      fullPath: '/app/sla-notifications'
      preLoaderRoute: typeof AuthenticatedAppSlaNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/sla-escalations': {
      id: '/_authenticated/app/sla-escalations'
      path: '/app/sla-escalations'
      fullPath: '/app/sla-escalations'
      preLoaderRoute: typeof AuthenticatedAppSlaEscalationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/sla-compliance': {
      id: '/_authenticated/app/sla-compliance'
      path: '/app/sla-compliance'
      fullPath: '/app/sla-compliance'
      preLoaderRoute: typeof AuthenticatedAppSlaComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/sla': {
      id: '/_authenticated/app/sla'
      path: '/app/sla'
      fullPath: '/app/sla'
      preLoaderRoute: typeof AuthenticatedAppSlaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/scheduled-exports': {
      id: '/_authenticated/app/scheduled-exports'
      path: '/app/scheduled-exports'
      fullPath: '/app/scheduled-exports'
      preLoaderRoute: typeof AuthenticatedAppScheduledExportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/reports': {
      id: '/_authenticated/app/reports'
      path: '/app/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/report-builder': {
      id: '/_authenticated/app/report-builder'
      path: '/app/report-builder'
      fullPath: '/app/report-builder'
      preLoaderRoute: typeof AuthenticatedAppReportBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/reorders': {
      id: '/_authenticated/app/reorders'
      path: '/app/reorders'
      fullPath: '/app/reorders'
      preLoaderRoute: typeof AuthenticatedAppReordersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/purchase-orders': {
      id: '/_authenticated/app/purchase-orders'
      path: '/app/purchase-orders'
      fullPath: '/app/purchase-orders'
      preLoaderRoute: typeof AuthenticatedAppPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/permissions': {
      id: '/_authenticated/app/permissions'
      path: '/app/permissions'
      fullPath: '/app/permissions'
      preLoaderRoute: typeof AuthenticatedAppPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/penalties': {
      id: '/_authenticated/app/penalties'
      path: '/app/penalties'
      fullPath: '/app/penalties'
      preLoaderRoute: typeof AuthenticatedAppPenaltiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/overview': {
      id: '/_authenticated/app/overview'
      path: '/app/overview'
      fullPath: '/app/overview'
      preLoaderRoute: typeof AuthenticatedAppOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/onboarding': {
      id: '/_authenticated/app/onboarding'
      path: '/app/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AuthenticatedAppOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/app/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/messages': {
      id: '/_authenticated/app/messages'
      path: '/app/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AuthenticatedAppMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/maintenance': {
      id: '/_authenticated/app/maintenance'
      path: '/app/maintenance'
      fullPath: '/app/maintenance'
      preLoaderRoute: typeof AuthenticatedAppMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/invoices': {
      id: '/_authenticated/app/invoices'
      path: '/app/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AuthenticatedAppInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/inventory': {
      id: '/_authenticated/app/inventory'
      path: '/app/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AuthenticatedAppInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/integrations': {
      id: '/_authenticated/app/integrations'
      path: '/app/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AuthenticatedAppIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/housekeeping': {
      id: '/_authenticated/app/housekeeping'
      path: '/app/housekeeping'
      fullPath: '/app/housekeeping'
      preLoaderRoute: typeof AuthenticatedAppHousekeepingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/guest-issues': {
      id: '/_authenticated/app/guest-issues'
      path: '/app/guest-issues'
      fullPath: '/app/guest-issues'
      preLoaderRoute: typeof AuthenticatedAppGuestIssuesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/docs': {
      id: '/_authenticated/app/docs'
      path: '/app/docs'
      fullPath: '/app/docs'
      preLoaderRoute: typeof AuthenticatedAppDocsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/delivery-queue': {
      id: '/_authenticated/app/delivery-queue'
      path: '/app/delivery-queue'
      fullPath: '/app/delivery-queue'
      preLoaderRoute: typeof AuthenticatedAppDeliveryQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/delegations-history': {
      id: '/_authenticated/app/delegations-history'
      path: '/app/delegations-history'
      fullPath: '/app/delegations-history'
      preLoaderRoute: typeof AuthenticatedAppDelegationsHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/delegations': {
      id: '/_authenticated/app/delegations'
      path: '/app/delegations'
      fullPath: '/app/delegations'
      preLoaderRoute: typeof AuthenticatedAppDelegationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/delegation-audit': {
      id: '/_authenticated/app/delegation-audit'
      path: '/app/delegation-audit'
      fullPath: '/app/delegation-audit'
      preLoaderRoute: typeof AuthenticatedAppDelegationAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/cost-analytics': {
      id: '/_authenticated/app/cost-analytics'
      path: '/app/cost-analytics'
      fullPath: '/app/cost-analytics'
      preLoaderRoute: typeof AuthenticatedAppCostAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/contracts': {
      id: '/_authenticated/app/contracts'
      path: '/app/contracts'
      fullPath: '/app/contracts'
      preLoaderRoute: typeof AuthenticatedAppContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/cashbook': {
      id: '/_authenticated/app/cashbook'
      path: '/app/cashbook'
      fullPath: '/app/cashbook'
      preLoaderRoute: typeof AuthenticatedAppCashbookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/audit': {
      id: '/_authenticated/app/audit'
      path: '/app/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AuthenticatedAppAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/assets': {
      id: '/_authenticated/app/assets'
      path: '/app/assets'
      fullPath: '/app/assets'
      preLoaderRoute: typeof AuthenticatedAppAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/area-mapping': {
      id: '/_authenticated/app/area-mapping'
      path: '/app/area-mapping'
      fullPath: '/app/area-mapping'
      preLoaderRoute: typeof AuthenticatedAppAreaMappingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/alerts': {
      id: '/_authenticated/app/alerts'
      path: '/app/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AuthenticatedAppAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/sla-notify': {
      id: '/api/public/hooks/sla-notify'
      path: '/api/public/hooks/sla-notify'
      fullPath: '/api/public/hooks/sla-notify'
      preLoaderRoute: typeof ApiPublicHooksSlaNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sla-escalations': {
      id: '/api/public/hooks/sla-escalations'
      path: '/api/public/hooks/sla-escalations'
      fullPath: '/api/public/hooks/sla-escalations'
      preLoaderRoute: typeof ApiPublicHooksSlaEscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/report-scheduler': {
      id: '/api/public/hooks/report-scheduler'
      path: '/api/public/hooks/report-scheduler'
      fullPath: '/api/public/hooks/report-scheduler'
      preLoaderRoute: typeof ApiPublicHooksReportSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/contracts-notify': {
      id: '/api/public/hooks/contracts-notify'
      path: '/api/public/hooks/contracts-notify'
      fullPath: '/api/public/hooks/contracts-notify'
      preLoaderRoute: typeof ApiPublicHooksContractsNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/tickets/$id': {
      id: '/_authenticated/app/tickets/$id'
      path: '/$id'
      fullPath: '/app/tickets/$id'
      preLoaderRoute: typeof AuthenticatedAppTicketsIdRouteImport
      parentRoute: typeof AuthenticatedAppTicketsRoute
    }
    '/_authenticated/app/reorders/$id': {
      id: '/_authenticated/app/reorders/$id'
      path: '/$id'
      fullPath: '/app/reorders/$id'
      preLoaderRoute: typeof AuthenticatedAppReordersIdRouteImport
      parentRoute: typeof AuthenticatedAppReordersRoute
    }
    '/_authenticated/app/delivery-queue/$id': {
      id: '/_authenticated/app/delivery-queue/$id'
      path: '/$id'
      fullPath: '/app/delivery-queue/$id'
      preLoaderRoute: typeof AuthenticatedAppDeliveryQueueIdRouteImport
      parentRoute: typeof AuthenticatedAppDeliveryQueueRoute
    }
    '/_authenticated/app/assets/$id': {
      id: '/_authenticated/app/assets/$id'
      path: '/$id'
      fullPath: '/app/assets/$id'
      preLoaderRoute: typeof AuthenticatedAppAssetsIdRouteImport
      parentRoute: typeof AuthenticatedAppAssetsRoute
    }
    '/_authenticated/app/a/$qr': {
      id: '/_authenticated/app/a/$qr'
      path: '/app/a/$qr'
      fullPath: '/app/a/$qr'
      preLoaderRoute: typeof AuthenticatedAppAQrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAppAssetsRouteChildren {
  AuthenticatedAppAssetsIdRoute: typeof AuthenticatedAppAssetsIdRoute
}

const AuthenticatedAppAssetsRouteChildren: AuthenticatedAppAssetsRouteChildren =
  {
    AuthenticatedAppAssetsIdRoute: AuthenticatedAppAssetsIdRoute,
  }

const AuthenticatedAppAssetsRouteWithChildren =
  AuthenticatedAppAssetsRoute._addFileChildren(
    AuthenticatedAppAssetsRouteChildren,
  )

interface AuthenticatedAppDeliveryQueueRouteChildren {
  AuthenticatedAppDeliveryQueueIdRoute: typeof AuthenticatedAppDeliveryQueueIdRoute
}

const AuthenticatedAppDeliveryQueueRouteChildren: AuthenticatedAppDeliveryQueueRouteChildren =
  {
    AuthenticatedAppDeliveryQueueIdRoute: AuthenticatedAppDeliveryQueueIdRoute,
  }

const AuthenticatedAppDeliveryQueueRouteWithChildren =
  AuthenticatedAppDeliveryQueueRoute._addFileChildren(
    AuthenticatedAppDeliveryQueueRouteChildren,
  )

interface AuthenticatedAppReordersRouteChildren {
  AuthenticatedAppReordersIdRoute: typeof AuthenticatedAppReordersIdRoute
}

const AuthenticatedAppReordersRouteChildren: AuthenticatedAppReordersRouteChildren =
  {
    AuthenticatedAppReordersIdRoute: AuthenticatedAppReordersIdRoute,
  }

const AuthenticatedAppReordersRouteWithChildren =
  AuthenticatedAppReordersRoute._addFileChildren(
    AuthenticatedAppReordersRouteChildren,
  )

interface AuthenticatedAppTicketsRouteChildren {
  AuthenticatedAppTicketsIdRoute: typeof AuthenticatedAppTicketsIdRoute
}

const AuthenticatedAppTicketsRouteChildren: AuthenticatedAppTicketsRouteChildren =
  {
    AuthenticatedAppTicketsIdRoute: AuthenticatedAppTicketsIdRoute,
  }

const AuthenticatedAppTicketsRouteWithChildren =
  AuthenticatedAppTicketsRoute._addFileChildren(
    AuthenticatedAppTicketsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedAppAlertsRoute: typeof AuthenticatedAppAlertsRoute
  AuthenticatedAppAreaMappingRoute: typeof AuthenticatedAppAreaMappingRoute
  AuthenticatedAppAssetsRoute: typeof AuthenticatedAppAssetsRouteWithChildren
  AuthenticatedAppAuditRoute: typeof AuthenticatedAppAuditRoute
  AuthenticatedAppCashbookRoute: typeof AuthenticatedAppCashbookRoute
  AuthenticatedAppContractsRoute: typeof AuthenticatedAppContractsRoute
  AuthenticatedAppCostAnalyticsRoute: typeof AuthenticatedAppCostAnalyticsRoute
  AuthenticatedAppDelegationAuditRoute: typeof AuthenticatedAppDelegationAuditRoute
  AuthenticatedAppDelegationsRoute: typeof AuthenticatedAppDelegationsRoute
  AuthenticatedAppDelegationsHistoryRoute: typeof AuthenticatedAppDelegationsHistoryRoute
  AuthenticatedAppDeliveryQueueRoute: typeof AuthenticatedAppDeliveryQueueRouteWithChildren
  AuthenticatedAppDocsRoute: typeof AuthenticatedAppDocsRoute
  AuthenticatedAppGuestIssuesRoute: typeof AuthenticatedAppGuestIssuesRoute
  AuthenticatedAppHousekeepingRoute: typeof AuthenticatedAppHousekeepingRoute
  AuthenticatedAppIntegrationsRoute: typeof AuthenticatedAppIntegrationsRoute
  AuthenticatedAppInventoryRoute: typeof AuthenticatedAppInventoryRoute
  AuthenticatedAppInvoicesRoute: typeof AuthenticatedAppInvoicesRoute
  AuthenticatedAppMaintenanceRoute: typeof AuthenticatedAppMaintenanceRoute
  AuthenticatedAppMessagesRoute: typeof AuthenticatedAppMessagesRoute
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppOnboardingRoute: typeof AuthenticatedAppOnboardingRoute
  AuthenticatedAppOverviewRoute: typeof AuthenticatedAppOverviewRoute
  AuthenticatedAppPenaltiesRoute: typeof AuthenticatedAppPenaltiesRoute
  AuthenticatedAppPermissionsRoute: typeof AuthenticatedAppPermissionsRoute
  AuthenticatedAppPurchaseOrdersRoute: typeof AuthenticatedAppPurchaseOrdersRoute
  AuthenticatedAppReordersRoute: typeof AuthenticatedAppReordersRouteWithChildren
  AuthenticatedAppReportBuilderRoute: typeof AuthenticatedAppReportBuilderRoute
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppScheduledExportsRoute: typeof AuthenticatedAppScheduledExportsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppSlaRoute: typeof AuthenticatedAppSlaRoute
  AuthenticatedAppSlaComplianceRoute: typeof AuthenticatedAppSlaComplianceRoute
  AuthenticatedAppSlaEscalationsRoute: typeof AuthenticatedAppSlaEscalationsRoute
  AuthenticatedAppSlaNotificationsRoute: typeof AuthenticatedAppSlaNotificationsRoute
  AuthenticatedAppSlaSettingsRoute: typeof AuthenticatedAppSlaSettingsRoute
  AuthenticatedAppSmartInboxRoute: typeof AuthenticatedAppSmartInboxRoute
  AuthenticatedAppStatisticsRoute: typeof AuthenticatedAppStatisticsRoute
  AuthenticatedAppStructureKpiRoute: typeof AuthenticatedAppStructureKpiRoute
  AuthenticatedAppStructuresRoute: typeof AuthenticatedAppStructuresRoute
  AuthenticatedAppSuppliersRoute: typeof AuthenticatedAppSuppliersRoute
  AuthenticatedAppSuppliersComplianceRoute: typeof AuthenticatedAppSuppliersComplianceRoute
  AuthenticatedAppSustainabilityRoute: typeof AuthenticatedAppSustainabilityRoute
  AuthenticatedAppTicketsRoute: typeof AuthenticatedAppTicketsRouteWithChildren
  AuthenticatedAppTrendsRoute: typeof AuthenticatedAppTrendsRoute
  AuthenticatedAppUsersRoute: typeof AuthenticatedAppUsersRoute
  AuthenticatedAppUtilitiesRoute: typeof AuthenticatedAppUtilitiesRoute
  AuthenticatedAppWorkOrdersRoute: typeof AuthenticatedAppWorkOrdersRoute
  AuthenticatedAppWorkflowsRoute: typeof AuthenticatedAppWorkflowsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAQrRoute: typeof AuthenticatedAppAQrRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedAppAlertsRoute: AuthenticatedAppAlertsRoute,
  AuthenticatedAppAreaMappingRoute: AuthenticatedAppAreaMappingRoute,
  AuthenticatedAppAssetsRoute: AuthenticatedAppAssetsRouteWithChildren,
  AuthenticatedAppAuditRoute: AuthenticatedAppAuditRoute,
  AuthenticatedAppCashbookRoute: AuthenticatedAppCashbookRoute,
  AuthenticatedAppContractsRoute: AuthenticatedAppContractsRoute,
  AuthenticatedAppCostAnalyticsRoute: AuthenticatedAppCostAnalyticsRoute,
  AuthenticatedAppDelegationAuditRoute: AuthenticatedAppDelegationAuditRoute,
  AuthenticatedAppDelegationsRoute: AuthenticatedAppDelegationsRoute,
  AuthenticatedAppDelegationsHistoryRoute:
    AuthenticatedAppDelegationsHistoryRoute,
  AuthenticatedAppDeliveryQueueRoute:
    AuthenticatedAppDeliveryQueueRouteWithChildren,
  AuthenticatedAppDocsRoute: AuthenticatedAppDocsRoute,
  AuthenticatedAppGuestIssuesRoute: AuthenticatedAppGuestIssuesRoute,
  AuthenticatedAppHousekeepingRoute: AuthenticatedAppHousekeepingRoute,
  AuthenticatedAppIntegrationsRoute: AuthenticatedAppIntegrationsRoute,
  AuthenticatedAppInventoryRoute: AuthenticatedAppInventoryRoute,
  AuthenticatedAppInvoicesRoute: AuthenticatedAppInvoicesRoute,
  AuthenticatedAppMaintenanceRoute: AuthenticatedAppMaintenanceRoute,
  AuthenticatedAppMessagesRoute: AuthenticatedAppMessagesRoute,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppOnboardingRoute: AuthenticatedAppOnboardingRoute,
  AuthenticatedAppOverviewRoute: AuthenticatedAppOverviewRoute,
  AuthenticatedAppPenaltiesRoute: AuthenticatedAppPenaltiesRoute,
  AuthenticatedAppPermissionsRoute: AuthenticatedAppPermissionsRoute,
  AuthenticatedAppPurchaseOrdersRoute: AuthenticatedAppPurchaseOrdersRoute,
  AuthenticatedAppReordersRoute: AuthenticatedAppReordersRouteWithChildren,
  AuthenticatedAppReportBuilderRoute: AuthenticatedAppReportBuilderRoute,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppScheduledExportsRoute: AuthenticatedAppScheduledExportsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppSlaRoute: AuthenticatedAppSlaRoute,
  AuthenticatedAppSlaComplianceRoute: AuthenticatedAppSlaComplianceRoute,
  AuthenticatedAppSlaEscalationsRoute: AuthenticatedAppSlaEscalationsRoute,
  AuthenticatedAppSlaNotificationsRoute: AuthenticatedAppSlaNotificationsRoute,
  AuthenticatedAppSlaSettingsRoute: AuthenticatedAppSlaSettingsRoute,
  AuthenticatedAppSmartInboxRoute: AuthenticatedAppSmartInboxRoute,
  AuthenticatedAppStatisticsRoute: AuthenticatedAppStatisticsRoute,
  AuthenticatedAppStructureKpiRoute: AuthenticatedAppStructureKpiRoute,
  AuthenticatedAppStructuresRoute: AuthenticatedAppStructuresRoute,
  AuthenticatedAppSuppliersRoute: AuthenticatedAppSuppliersRoute,
  AuthenticatedAppSuppliersComplianceRoute:
    AuthenticatedAppSuppliersComplianceRoute,
  AuthenticatedAppSustainabilityRoute: AuthenticatedAppSustainabilityRoute,
  AuthenticatedAppTicketsRoute: AuthenticatedAppTicketsRouteWithChildren,
  AuthenticatedAppTrendsRoute: AuthenticatedAppTrendsRoute,
  AuthenticatedAppUsersRoute: AuthenticatedAppUsersRoute,
  AuthenticatedAppUtilitiesRoute: AuthenticatedAppUtilitiesRoute,
  AuthenticatedAppWorkOrdersRoute: AuthenticatedAppWorkOrdersRoute,
  AuthenticatedAppWorkflowsRoute: AuthenticatedAppWorkflowsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAQrRoute: AuthenticatedAppAQrRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  GQrRoute: GQrRoute,
  ApiTtsSpeakRoute: ApiTtsSpeakRoute,
  ApiPublicHooksContractsNotifyRoute: ApiPublicHooksContractsNotifyRoute,
  ApiPublicHooksReportSchedulerRoute: ApiPublicHooksReportSchedulerRoute,
  ApiPublicHooksSlaEscalationsRoute: ApiPublicHooksSlaEscalationsRoute,
  ApiPublicHooksSlaNotifyRoute: ApiPublicHooksSlaNotifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
